name: Half-year calendar

on:
 schedule:
   - cron: "0 0 * * *" 
 workflow_dispatch:
 push:
   branches:
     - main
     
jobs:
 generate:
   permissions:
     contents: write
   runs-on: ubuntu-latest
   timeout-minutes: 5

   steps:
     # Checkout the repository
     - name: Checkout repository
       uses: actions/checkout@v3
      # Generate repositories
      



   
